services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_PASSWORD: go
    ports:
      - 5433:5432
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
