// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>PHIN VADS Home</h1><div class=\"search\"><p>Search PHIN VADS</p><div class=\"search-input\"><button>Search</button></div></div><h2>Hot Topics</h2><div class=\"hot-topics\"><button class=\"accordion\">PHIN VADS Feedback</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">New CDCREC Code System Status Upate</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">CDC Race Category and Ethnicity Group</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">COVID-19 Information Management Response (VADS)</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.1 General COVID-19 Information Management Response</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.2 Representing Health Care Data for Emergency Medical Services</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.3 Patient's Clinical Encounter</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.4 COVID-19 Public Health Reporting</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.5 Labratory Data Exchange and Labratory Surveillance</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.6 Geospatial Data Set and Tools</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.7 COVID-19 Immunization</button><div class=\"panel\"><p>Lorem ipsum...</p></div><button class=\"accordion\">1.8 Community Resilience and Social Determinants of Health (SDOH)</button><div class=\"panel\"><p>Lorem ipsum...</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
