// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UsaBanner(action string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"usa-banner\" class=\"cdc-page-banner container noindex\" aria-label=\"Official website of the United States government\"><div class=\"row cdc-site-gov-notice noindex noprint\"><div class=\"col-lg-11\"><div class=\"\"><img aria-hidden=\"true\" class=\"usa-banner__header-flag\" src=\"/assets/img/us_flag_small.png\" alt=\"U.S. flag\" width=\"16\" height=\"11\"> <span>An official website of the United States government</span></div><span><button")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if action == "close" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" hx-get=\"/toggle-banner/open\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" hx-get=\"/toggle-banner/close\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" hx-trigger=\"click\" hx-target=\"#usa-banner\" hx-swap=\"outerHTML\" data-bs-toggle=\"collapse\" class=\"usa-banner__toggle usa-banner__header-action\" aria-controls=\"usa-accordion__content\">Here's how you know </button></span></div><div")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if action == "close" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"collapse hide usa-accordion__content\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"collapse show usa-accordion__content\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" id=\"gov-notice\"><div class=\"row\"><div class=\"col-12 col-lg-6\"><img src=\"/assets/img/icon-dot-gov.svg\" alt=\"\" aria-hidden=\"true\"><div class=\"usa-banner__content-text\"><b>Official websites use .gov</b><p>A .gov website belongs to an official government organization in the United States.</p></div></div><div class=\"col-12 col-lg-6\"><img src=\"/assets/img/icon-https.svg\" alt=\"\" aria-hidden=\"true\"><div class=\"usa-banner__content-text\"><b>Secure .gov websites use HTTPS</b><p>A  <strong>lock</strong> (<span><img src=\"/assets/img/lock.svg\" class=\"lock-img\"></span>)  or  <span><strong>https://</strong></span> means you've safely connected to the .gov website. Share sensitive information only on official, secure websites.</p></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
